## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Colors configuration
colors:
    primary:
      background: '0x1d2021'
      foreground: '0xd4be98'
    normal:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  # # Default colors
  # primary:
  #   background: '#1e222a'
  #   foreground: '#c8ccd4'

  # # Normal colors
  # normal:
  #   black:   '#1e222a'
  #   red:     '#e06c75'
  #   green:   '#98c379'
  #   yellow:  '#e5c07b'
  #   blue:    '#61afef'
  #   magenta: '#c678dd'
  #   cyan:    '#56b6c2'
  #   white:   '#abb2bf'

  # # Bright colors
  # bright:
  #   black:   '#545862'
  #   red:     '#e06c75'
  #   green:   '#98c379'
  #   yellow:  '#e5c07b'
  #   blue:    '#61afef'
  #   magenta: '#c678dd'
  #   cyan:    '#56b6c2'
  #   white:   '#c8ccd4'
