#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Script To Manage Brightness For Archcraft.

# icons
iDIR='/home/mrrobot/.config/dwm/icons/'

# Graphics card
CARD=`ls /sys/class/backlight | head -n 1`

no_xbacklight() {
  output=$(xbacklight 2>&1) # 2>&1 to also capture stderr
  expected_output="No outputs have backlight property"
  
  if [[ $output == $expected_output ]]; then
    return 0
  else
    return 1
  fi
}


# Get brightness
get_backlight() {
	if [[ no_xbacklight ]]; then
	    brightnessctl info | grep -oP '(?<=\().*(?=\))'
	else
		BNESS=`xbacklight -get`
		LIGHT=${BNESS%.*}
	fi
	echo "${LIGHT}"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR"/brightness-20.png
	elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
		icon="$iDIR"/brightness-40.png
	elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
		icon="$iDIR"/brightness-60.png
	elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
		icon="$iDIR"/brightness-80.png
	elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
		icon="$iDIR"/brightness-100.png
	fi
}

# Notify 
notify_bl() {
	get_icon && dunstify -u low --replace=69 -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	if [[ "$CARD" == *"intel_"* ]]; then
		new=$(brightnessctl set +100)
	else
		light -A 5 && notify_bl
	fi
}

# Decrease brightness
dec_backlight() {
	if [[ no_xbacklight ]]; then
		new=$(brightnessctl set 100-) && notify_bl
	else
		xbacklight -dec 10 && notify_bl
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
